services:
    web:
        build: .
        ports:
            - "80:80"
        volumes:
            - ./laravel_app:/var/www/html
        depends_on:
            - db
            - mailpit
    db:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: laravel
            MYSQL_USER: laraveluser
            MYSQL_PASSWORD: laravelpass
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
    mailpit:
        image: axllent/mailpit
        ports:
            - "8025:8025"
            - "1025:1025"

volumes:
    dbdata:
